### PR TITLE
Fix #142

### LINKED ISSUE #142: Problem on iterating ArrayList
```
λ ~/venv/ python -V
Python 2.7.9
λ ~/venv/ cat test.py
import jpype
jpype.startJVM(jpype.getDefaultJVMPath())

arr = jpype.java.util.ArrayList()
l = [i for i in arr]
λ ~/venv/source jpype0.5.7/bin/activate
(jpype0.5.7)λ ~/venv/ python test.py
(jpype0.5.7)λ ~/venv/ deactivate
λ ~/venv/source jpype0.6.0/bin/activate
(jpype0.6.0)λ ~/venv/ python test.py
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    l = [i for i in arr]
  File "/home/dwshin/venv/jpype0.6.0/local/lib/python2.7/site-packages/jpype/_jcollection.py", line 32, in __next__
    return next(self.iterator)
RuntimeError: No matching overloads found. at native/common/jp_method.cpp:121
```

### PR DESCRIPTION
**Pull request by littmus**

### CODE REVIEW

**Comment by baztian** [comment]
Thanks! Can you please write a unit test for the feature?

**Comment by littmus** [comment]
What test do you mean? It's not a feature.
Just fix the problem that worked in previous version but not working in current version.

**Comment by baztian** [comment]
You could add a unit test to test/jpypetest similar to the existing tests. Maybe collection.py. Similar to the sample you provided for the issue but with some unit assert method calls.

As the tests were always passing we obviously don't have an existing test for your issue.

**Comment by baztian** [comment]
Also it would be nice if you can add a comment to the doc/CHANGELOG.rst and if you want to AUTHORS.rst.

**Comment by littmus** [comment]
Umm.. I can't sure that I understood the code enough to write the test.
Anyway I'll take a look at it.

**Comment by kutschkem** [comment]
Just use the code that failed as test.

**Comment by baztian** [comment]
@littmus what is  9e88eef "fix some problems" for? What kind of problems does it fix?

**Comment by littmus** [comment]
@baztian Sorry for my ambiguous commit message.
https://github.com/originell/jpype/commit/1c0b7c02586a48583906b09d20a5d09d55b7ac1e had a py2 and py3 compatibility problem.

**Comment by baztian** [comment]
This should be fixed via #147.

**Pull request merged**
