### PR TITLE
[deployment] push wheels for 32/64 bit to pypi

### PR DESCRIPTION
**Pull request by marscher**
on a tagged commit the resulting binary wheel will be pushed to pypi. I've created an extra pypi user for that and granted him maintenance role. @originell I think there is still no appveyor hook for this repo, which needs to be activated so if release (tag) a new version the automatic deployment is being triggered.

### CODE REVIEW

**Comment by baztian** [comment]
Would be awesome to have this in a working state. Why is the "AppVeyor build failed"?

**Comment by originell** [comment]
any updates here? maybe something I can do to make the build not fail? (meaning maybe some integration fail on my side)

**Comment by baztian** [comment]
@originell I think you have to go to http://www.appveyor.com/ "sign in with github" and add jpype as a project. Anything else @marscher ?

**Comment by marscher** [comment]
we have to add a pypi user with push access and encrypt its credentials in travis and appveyor to be able to automatically deploy

**Comment by originell** [comment]
okay.. does anyone of you already have access to pypi to do this? or should i?

**Comment by marscher** [comment]
I have added some credentials. Now we have to fix the testsuite under windows. There are some conversions failing for Numpy and string conversion returns unicode instead of plain string (expected by test).

**Comment by baztian** [comment]
If the testsuite is fixed #87 could be closed.

**Comment by baztian** [comment]
If it is too complicated to fix the testsuite now you could @unittest.skipIf(IS_WIN) or something.

**Comment by marscher** [comment]
I mean the tests are failing for a reason. And we (or I) shoulf fix that, before releasing binaries containing these bugs :+1:

**Comment by baztian** [comment]
I think it is better to have binary builds with some issues rather than having no binary builds at all. If one builds the binaries by himself the problem still exists.

What about opening a issue for the Windows bugs and integrating appveyor support with some skipped tests?

**Comment by baztian** [comment]
BTW: Please don't forget to add a Changelog entry.

**Comment by caspervdw** [comment]
Hi, 
This may be related: I am working on the distribution of PIMS, that uses JPype to interface with a set of image readers that are written in java (bioformats). In order to make this more accessible for our windows users, I would like to try to make a recipe for jpype at conda-forge. This would build the binaries automatically for Windows, OSX, and Linux which can be installed easily by conda users.

Is anyone interested in assisting me with possible build issues, and maintaining this build recipe for future versions?

**Comment by marscher** [comment]
Hi,


going for conda-forge is a very good idea! I can help out, if there are 
issues.

**Comment by marscher** [comment]
you can use some of these info here, but conda-forge uses a slightly different style.
```
about: {home: 'https://github.com/originell/jpype/', license: Apache Software License,
  summary: A Python to Java bridge.}
build:
  entry_points: []
  features: []
  string: ''
  track_features: []
package: {name: jpype1, version: 0.5.7}
requirements:
  build: [python, setuptools, numpy]
  conflicts: []
  run: [python, numpy]
source:
  fn: JPype1-0.5.7.tar.gz
  git_rev: ''
  md5: 71333b39aca9fd08b6d0515bfc6c1d62
  patches: []
  path: ''
  svn_rev: ''
  url: https://pypi.python.org/packages/source/J/JPype1/JPype1-0.5.7.tar.gz
test:
  commands: []
  files: []
  imports: [jpype]
  requires: []
```

**Comment by marscher** [comment]
sorry I should have posted this one:
```
package:
  name: jpype1
  version: !!str 0.5.7

source:
  fn: JPype1-0.5.7.tar.gz
  url: https://pypi.python.org/packages/source/J/JPype1/JPype1-0.5.7.tar.gz
  md5: 71333b39aca9fd08b6d0515bfc6c1d62 

requirements:
  build:
    - python
    - setuptools
    - numpy
  run:
    - python
    - numpy

test:
  imports:
    - jpype

about:
  home: https://github.com/originell/jpype/
  license: 'Apache Software License'
  summary: 'A Python to Java bridge.'

```

**Pull request closed without merging**
