### PR TITLE
Feature/python3 compatibility4

### PR DESCRIPTION
**Pull request by kristi**
initial stab at Python3 compatibility

proxy unit tests cause segfault, but other unit tests pass

Tested on OSX 10.9 / (pyenv) Python 2.6, 2.7, 3.4

issue #119

### CODE REVIEW

**Comment by marscher** [comment]
can you edit your .travis.yml and add python 3 to the build matrix?

**Comment by baztian** [comment]
Fantastic news! Good work @kristi!
The proxy tests did pass using our .py files with .so from tcalmant's fork as far as I remember. Maybe you can spot the relevant delta there...

**Comment by marscher** [comment]
http://docs.travis-ci.com/user/languages/python/

Maybe you could also add 3.3?

**Comment by marscher** [comment]
super cool! The tests are all running, very impressive! Have you also checked already if there are any memory leaks under Py3?

**Comment by kristi** [comment]
No, I haven't checked for memory leaks yet. Do you have any recommended
tools or methods?

**Comment by baztian** [comment]
I think we can merge that pull request, can't we? I would suggest to release a 0.6 (`bumpversion minor`) as Python 3 support is really a big new feature. If there are memory leaks they can be fixed later on. Thanks @kristi for making the cpp part. Absolutely awesome!

**Comment by baztian** [comment]
Oh, I forgot something: We have to update the README and the documentation (still stating if you're looking for py 3 use the tcalmant version...)

**Comment by marscher** [comment]
thank you very much @kristi! I will run some valgrind checks on the testsuite soon.

**Comment by marscher** [comment]
valgrind reported no (new) issues. Only leaks in JVM8 itself, which we can not fix :+1:

**Pull request merged**
