### PR TITLE
Patch to fix Class.forName()

### PR DESCRIPTION
**Pull request by Thrameos**
This was a fairly difficult modification as customizers do not support changing fields.  I introduced an enhanced customizer as best I could.  This allows direct adjustment of fields.   This addresses the defective forName()

### CODE REVIEW

**Comment by Thrameos** [comment]
Shelving this one for now until I get proper support of java.lang.Class.  No sense in allowing something which does not yet point to the correct object type.

**Comment by marscher** [comment]
I'm kinda puzzled by the fact that removing the topological sorting for member lookups did not break anything. I think this was introduced to properly support multi-inheritance.

**Comment by Thrameos** [comment]
I don't think that I changed the sorting or at least not intentionally.  The mro got moved from 202 in the previous to 204 in the revised.    The move up (relative to the customizers) was so that the customizer has access to all of the fields.  I can move it back to the original if you feel that it should be an unconditional setting.

**Comment by marscher** [comment]
ah my fault :)

**Comment by Thrameos** [comment]
Okay.  Though I still recommend holding this patch until I can finish work so that forName() returns a java.lang.Class.

**Pull request merged**
