### PR TITLE
Cygwin + Appveyor (take 3)

### PR DESCRIPTION
**Pull request by Thrameos**
Okay another attempt at this.  Unfortunately I may have screwed up my fork on a bad pull.  So it this one doesn't work I will have to go back and restart from scratch.

### CODE REVIEW

**Comment by marscher** [comment]
sorry I don't really get what the purpose of this is. Are you combining all the previous work in one PR?

**Comment by Thrameos** [comment]
This one should just be the cygwin patch.   Attempting to get the rebase correct.  Unfortunately, I am not the best at git.

**Comment by marscher** [comment]
make sure your local master branch is up to date, then checkout your cygwin working branch and run git rebase master.

**Comment by Thrameos** [comment]
Hmm.  The problem is I must have done a merge by mistake.  I run "git rebase upstream/master" run through the rebase, do a "git push", it is rejected, then "git pull", then "git push".  The push does refuses at that point as no changes rather that marking me to be properly rebased.

**Comment by marscher** [comment]
the push is of course rejected because the history of your forks upstream can not match the local one (rebase rewrites the history). So you have to do a force push. If you are not sure about this, you should backup the remote branch prior force pushing.

**Comment by Thrameos** [comment]
Okay thanks.  I will try a force push and then rebase each of the pull requests.

**Pull request closed without merging**
