### PR TITLE
Attempt to fix proxy thread issue.

### PR DESCRIPTION
**Pull request by Thrameos**
This patch makes Callbacks more exception safe.  Unfortunately, it doesn't fix the current threading problem in proxy.

### CODE REVIEW

**Comment by Thrameos** [comment]
This is in reference to #299

**Comment by Thrameos** [comment]
Rebased to master.

**Comment by Thrameos** [comment]
A green arrow. :heavy_check_mark:   Happy days!!! :checkered_flag:

**Comment by marscher** [comment]
Thanks, this is the right pattern to do it.

**Pull request merged**
