### PR TITLE
On cygwin use /proc/registry to find jvm instead winreg 

### PR DESCRIPTION
**Pull request by Thrameos**
Pull request for #293

### CODE REVIEW

**Comment by marscher** [comment]
```
In file included from native/common/include/jp_utility.h:20:0,
                 from native/common/include/jpype.h:133,
                 from native/common/jp_array.cpp:17:
native/jni_include/jni.h:61:22: error: conflicting declaration 'typedef int64_t jlong'
     typedef int64_t  jlong;    /* signed 64 bits */
                      ^~~~~
In file included from native/common/jp_array.cpp:17:0:
native/common/include/jpype.h:82:21: note: previous declaration as 'typedef long long int jlong'
   typedef long long jlong;
                     ^~~~~
error: command 'gcc' failed with exit status 1
```

**Comment by marscher** [comment]
I think the typedef in jpype.h is not meant to be there.

**Comment by rliebscher** [comment]
I guess the compiler error related comments should really go pull request #302 ?

**Comment by Thrameos** [comment]
Rebased to master.

**Pull request merged**
