### PR TITLE
improve error message for failed overload matching

### PR DESCRIPTION
**Pull request by kutschkem**
addresses #140 
This is not perfect, but shows the direction in which the error messages should go in my opinion. Even better would be to include the signature that the method tried to match. Hints at how to best achieve this would be appreciated ;-)

### CODE REVIEW

**Comment by marscher** [comment]
have a look at the matchreport method. It shows how to obtain the argument types.

**Comment by kutschkem** [comment]
Actually, I can find no place where the HostRef is transformed to a String. I see I can query HostEnv about it, but can I also get the type? I can't even find a way to convert HostRef to JType. All the instances I have seen are a JType checking that the HostRef can be converted to it, the JType converting it. In order to properly display what arguments were given, I need to be able to print the type without having a signature beforehand, if that makes sense.

**Comment by baztian** [comment]
Your pull request doesn't compile. See the [Travis output](https://travis-ci.org/originell/jpype/jobs/67965695).

**Comment by marscher** [comment]
Think this has been addressed by #172

**Pull request closed without merging**
